### ISSUE TITLE
The promotion system.

### ISSUE THREAD

**Issue by Alya-N** [Alya-N/C-Hero-Calc#10]
**EDIT:**
Promotion system is ready.
Use hawking:99.5 for promotions.
Detailed change log is here https://github.com/Alya-N/C-Hero-Calc/compare/4.0.0.0a_backup...Alya-N:Promotions_beta

I doubt I'll be able to implement [the promotion system](https://www.kongregate.com/forums/910715-cosmos-quest/topics/1783352-upcoming-content-christmas-2018) in a reasonable amount of time (I'll try, but it'll take a while(months?) and is not 100% certain I have the skill required for it). For anyone who decides to update the calc, I'll leave some notes from room 1.
```
 PiratePete: Minion, Alya, you're gonna need to decide what sort of notation to use in Calc. 
I suggest the letters a --> e at the end of a Heros level, 
so if I had 2 promotions on aTr0n1x, I'd enter it as atr0n1x:99b

SnKKermit: Lepr will always assume your opponent has 1 more enemy than they do. 
PiratePete: Lep solo vs WB.
PiratePete: BOOM!
PiratePete: Broken!
SnKKermit: Nope, cause it won't work vs WB. 

lollerblade1: can't wait to face it in dq
SnKKermit: You won't experience promoted heroes in DQ for a while loller.
SnKKermit: You'll have to get through Ascended 1ks first 

lollerblade1: dg, i did a trick 
lollerblade1: update the cqdata file
lollerblade1: change the base stats 
lollerblade1: and then use level 1 
lollerblade1: in the macro
lollerblade1: instead of 99 
lollerblade1: for aathos, just remove the _L, set the armor to 30, and use level 1 again 
lollerblade1: same for abavah, aauri and stuff 
```
So, from what I can tell, the parsing system and the replay generator will have to be altered. Macrocreator also needs to be changed to accommodate the new feature and the new promotions will have to be retrieved from the server.

_(Oh, and I've already made preparations for Christmas heroes here: https://github.com/Alya-N/C-Hero-Calc/compare/3.2.2.0f_Backup...Alya-N:master )_

**Comment by robgw84** [comment]
I think all but the last stage of the promotion system would actually be fairly easy to implement. Once you are able to retrieve the promotion level then you could just add the stats to it, it seems that each hero has different stats for the 1st, 2nd and 4th stage, but the 3rd stage is 1 stats per level for common, 2 stats per level for rare and 3 stats per level for legendary, which since they have to be level 99 would be 99 stats (both atk and hp I believe) for common, 198 for rare and 297 for legendary.

I think the promotion system is actually easier than dealing with the abilities of new heroes.

**Comment by Alya-N** [comment]
Okay, I may have made a test build of the promotion system: https://github.com/Alya-N/C-Hero-Calc/tree/Promotions_beta
Use hawking:99.5 for promotions.
