### ISSUE TITLE
Ruin's AoE Revenge

### ISSUE THREAD

**Issue by Farario** [Alya-N/C-Hero-Calc#17]
Calc suggests using Werewolf as the last unit alive in a line that goes up against Ruin, which according it, works out, but doesn't because 1k Ruin deals over 100 revenge aoe, which kills the werewolf.

**Comment by Alya-N** [comment]
Thank you. It will be worked on. 
It's a bit more complicated, since the changes to revenge skills are drastic compared to the old system. Revenge aoe is triggered in any position whether frontline or backline, and can trigger other revenge aoe. Fix might take some time.
Currently calc ignores reflect damage killing revenge as well, so that will also be part of a fix.

**Comment by Alya-N** [comment]
The latest calc update should have fixed it. Unfortunately, since you didn't provide a full enemy lineup and false positive, I can't mark it as solved yet.
EDIT: Nevermind, marking it as solved now, since I've modified revenge code and haven't seen any false positives.
