### ISSUE TITLE
Application crashes with exception code 0xc0000005

### ISSUE THREAD

**Issue by aurril** [Alya-N/C-Hero-Calc#21]
As mentioned in the title, the application crashes while calculating with the mentioned message in the windows event viewer.
Attached is the used hero configuration.
[gen.zip](https://github.com/Alya-N/C-Hero-Calc/files/2732688/gen.zip)

**Comment by Alya-N** [comment]
Thank you for the bug report. I believe the latest calc version fixed the underlying issue.
The bug occurred due to Kedari's implementation of self-AoE in calc. It was before Lux could count the number of alive units and determine the target. Therefore, Lux happened to go out of hero bounds when Kedari was the only unit left and AoE applied to him too early, so he died as well, leaving 0 alive heroes.
The details of a bug fix can be seen here: https://github.com/Alya-N/C-Hero-Calc/commit/5799115456adb2052423f9c129e184da036e963e
And here is the solution the latest version of calc provides now:
```
Solution for [Followers:       0 | groth:1000 lordkirk:1000 neil:1000 boor:1000 luxuriusmaximus:1000 <==]:
  [Followers:       0 | drhawking:99 masterlee:99 guy:99 athert:99 neil:99.5 cliodhna:99.5 <==]

  109502 Fights simulated.
  Total Calculation Time: 0
  Calc Version: 4.0.1.1m

Battle Replay (Use on Ingame Tournament Page):
eyJzZXR1cCI6Wy0xMDMsLTEwNCwtMTMyLC0xMjEsLTExNSwtMTMxXSwic2hlcm8iOnsiMTI5Ijo5OSwiMTEzIjo5OSwiMTE5Ijo5OSwiMTMwIjo5OSwiMTAyIjo5OSwiMTAxIjo5OX0sInNwcm9tbyI6eyIxMjkiOjUsIjExMyI6NX0sInBsYXllciI6Wy0zNywtNTksLTExNSwtOTYsLTExMCwtMV0sInBoZXJvIjp7IjEwOCI6MTAwMCwiOTQiOjEwMDAsIjExMyI6MTAwMCwiNTciOjEwMDAsIjM1IjoxMDAwfSwicHByb21vIjp7fX0=
```
