### ISSUE TITLE
Calculator Only Finding 4 Unit Solution

### ISSUE THREAD

**Issue by robgw84** [Alya-N/C-Hero-Calc#23]
The calculator is only returning solutions of 4 units for quests even if the quest doesn't have the 5 or 6 unit options done yet.

While this would normally be fine since doing the quest with 4 units completes all of them, it does not work very well if you are only trying to open up more quests by completing the 6 unit option. 

For example to promote Master Lee to tier 2 you need to beat quest 158, but if you haven't at least beaten 157 with 6 units then you cant even attempt 158. However even if you beat 157 with 6 units, you can still beat 158 with 4 (as in you don't have to complete all three options for a previous quest before doing the next quest).

It's not a huge issue, but it can prevent you from completing quests because the followers you gain from the 5 or 6 unit solutions may give you enough to complete the 4 unit one.

**Comment by robgw84** [comment]
Actually never mind, I may have found out why. The file you mentioned last time default.cqconfig was changed back so it may have been stopping at the first solution it found and ignoring others, I will test it to see.

**Comment by Alya-N** [comment]
Are you sure you're using the right quest suffix to get 6-unit solutions?

**-1** is for **6** unit solutions
**-2** is for **5** unit solutions
**-3** is for **4** unit solutions
**-4** is for **3** unit solutions (Usually used for promotion quests, though it doesn't force a hero that is being promoted to be in the solution)

The way the calc works is that it first looks for 1 unit solutions, then 2, then 3, 4, etc. If there is a 4 unit solution, it won't waste your time finding a solution that has 6 units, since a 4 unit solutions works just as well.

**Comment by robgw84** [comment]
I was specifically looking for -1 but it wouldn't go past 4 unit. The issue was the same as the last time when it was only showing me 2 unit solutions, I guess when the calculator was updated and I downloaded the update it changed that config file back so I had to change the TRUE to FALSE again.

I couldn't use the 4 unit solution that it found because I was seeing how many followers it would take to complete the 6 unit solution for the next quest and the 4 unit solution it was giving me was like 200 million followers higher than I have.

But changing it back to FALSE worked again.
