### ISSUE TITLE
Gives a draw

### ISSUE THREAD

**Issue by Vitae666** [Alya-N/C-Hero-Calc#28]
Solution for [Followers: 104,263,500 | mrcotton:46 a22 w21 e22 f22 <==]:
  [Followers:       0 | ageum:99.1 nebra:99.2 <==]

  81 Fights simulated.
  Total Calculation Time: 0
  Calc Version: 4.3.2.1c

Battle Replay (Use on Ingame Tournament Page):
432cAAo2MwLGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANquBVKhWK4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AA==

**Comment by Alya-N** [comment]
Except it wins in the replay you provided. Unless I'm not seeing something here?

**Comment by Vitae666** [comment]
That's the usual problem with the way the replay works on the site. You get a tie on the calc but win on site. The attack order changes. Known issue for a long time.
I should have thought to do a screenshot.

**Comment by Alya-N** [comment]
The attack order changes? I know there are some left-right side issues that haven't been fixed yet, but I'm not sure what you mean by attack order. I guess it's too late to ask now since the DQ is different.
And I couldn't replicate this issue through moving empty spots on the replay, since those sometimes affect the outcome as well.
The only way I managed to get a tie is by putting the enemy lineup backwards from what's shown in your bug report. Any other outcome was either a win or a loss.

**Comment by Vitae666** [comment]
Think that the left side attacks 1st rather than player? Or reversed? Can't
remember.
All I know is that there are a load of posts on CQ forums for the Calc that
show people lose or draw and the replay shows a different result.

**Comment by Alya-N** [comment]
Left side is the player, and both sides attack at the same time, aside from a few unintended interactions in the game (almost none of them have survived the battle reform though, which happened half a year ago)

Most of the forum posts are very old and the bugs mentioned there have been ironed out.
I've seen players report of the outcome being different in tournament draws because of the difference in damage calculated between server and client, the cause of which is unknown, and it is a very rare occurrence.

There are a few cases where there is a discrepancy between replay and in-game result, but that's usually because of where empty spaces were placed, and only specific heroes react to that (Lili for the ally side, Poker, Dice, Lux, Tetra for the enemy side), none of which are present in your example.

It would help if you could describe in detail how the in-game fight was different from the replay.

**Comment by Vitae666** [comment]
Wouldn't know how to describe it in detail.
The MacroCreator was stuck on a certain Daily. It would send the result. The result was accepted. The same DQ was returned.
I went into the game. Manually added ageum:99.1 nebra:99.2 and the result was a draw.
I ran the MC without sending the result so that I could get the replay code. I posted the code. You see a different result where I won. Which I didn't.
That's pretty much it. 
I added one extra hero just so that there was no Draw so I could continue using MC and go thru more DQ's.
Why it happened? I wouldn't know. It did. Otherwise I wouldn't have reported it. Bit of a waste of my time to pretend to have an error on my day off from work when my kids wanted to go to the park. :)

Maybe it's something with Mr. Cotton's AoE & Reflect?

**Comment by Alya-N** [comment]
I'm glad that you've provided the information about you using MacroCreator's auto-DQ feature. Sorry, but unfortunately there isn't much I can do in this situation.

I'm assuming that you actually saw the draw happen, and it wasn't a case of "it shows a win, but doesn't proceed", which seems extremely odd, considering that the code for the replays and the DQ fights you see in-game is the same. Unsure of what unseen factor could have altered that.

It is too late for this case, but I'm guessing to figure out this bug I would need to see the DQ version of the fight myself, either by encountering a similar bug (which is unlikely to happen, as I don't use auto-DQ), or by watching a video/gif of the fight (which would be inconvenient to make)

Still, thank you for reporting this bug.

**Comment by Vitae666** [comment]
Yeap. Like I said, I checked in game with the 2 heroes it gave and it gave
the draw.

How do you do the daily quests then? All manual? *Shudder*

Also, not to hard to do screenvids. There's something called
screencastomatic. I'd already gotten past that battle before I remembered
it.
https://screencast-o-matic.com/screen-recorder
Thing it you'd need to upload the file somewhere. Dropbox, Google drive or
something like that.

**Comment by Alya-N** [comment]
Yep, all manual. "Fight Max" usually gets me within 10 DQs from my stopping point. 
(Though for some people even that is not necessary, since they have Lucy Minions, which keeps their DQ level upon reset, just giving them a different enemy lineup for that level)

And thank you for recommending that screen-recording software. Looks useful :D
