### ISSUE TITLE
AHosokawa Promotion Quest quest151-4 Not correct :(

### ISSUE THREAD

**Issue by Vitae666** [Alya-N/C-Hero-Calc#36]
Current Version
[Followers: 1,830,521,500 | f35 ahosokawa:99.1 lili:99.2 <==]
460hAARd6xnc40AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJPoEd0A8Hg7HYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=

Draws on Play. Wins on Replay
http://youtu.be/3WFRJm7PSxo?hd=1

**Comment by Alya-N** [comment]
Lili's stats are based on where she's placed, and calc places empty spaces in front of the formation, not behind it. So it's actually `f35 ahosokawa:99.1 lili:99.2 empty empty empty <==`
I have to say though, Lili is an interesting choice to max. I hope you did it because you liked her design and wanted to have a cute mahou shoujo on your team.

**Comment by Vitae666** [comment]
Ah. Can the calc somehow indicate empty cells for when there's empty cells other than the last one(s)

**Comment by Alya-N** [comment]
Nope, it doesn't even consider shuffling empty cell location whenever there's an RNG hero in the enemy lineup, so all empty spaces are in front of the formation.
I'll try to see if I can add a note to calc with that info, but it might be hard to notice for some anyway among all the other calc output.
